### ISSUE TITLE
Verify GoReleaser publisher in Azure Marketplace

### ISSUE THREAD

**Issue by dirien** [goreleaser/goreleaser-azure-devops-extension#123]
### Is your feature request related to a problem? Please describe.

No.

### Describe the solution you'd like

It would be nice to verify our publisher, the process looks quite straight forward! Similar to GitHub (no wonder :D)

![image](https://user-images.githubusercontent.com/38325136/155198737-b7c2a54a-5b46-490e-8ce1-70a6a74d2db7.png)

https://code.visualstudio.com/api/working-with-extensions/publishing-extension#verify-a-publisher

### Describe alternatives you've considered

-

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Talked with @caarlos0 in discord about it

**Comment by caarlos0** [comment]
![Uploading image.png…]()


waiting :)

**Comment by dirien** [comment]
Yolo! Probably manually 😄

**Comment by caarlos0** [comment]
yeah

**Comment by dirien** [comment]
> Once your TXT record has been validated, the Marketplace team will review your request and grant verification within 5 business days.

lol

**Comment by dirien** [comment]
Done, thx @caarlos0! 
![image](https://user-images.githubusercontent.com/38325136/157728729-55c168f4-8cd5-42d3-8db4-98c93d9ba3e6.png)
