### ISSUE TITLE
Update Axiom to >1.x

### ISSUE THREAD

**Issue by dirien** [goreleaser/goreleaser-azure-devops-extension#328]
### Is your feature request related to a problem? Please describe.

Releates to https://github.com/goreleaser/goreleaser-azure-devops-extension/pull/326

Currently Azure DevOps Hosted agent run on Node 10. This blocks the update of some of our libraries in this plugin.

### Describe the solution you'd like

-

### Describe alternatives you've considered

-

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Adding @caarlos0 so he is in the loop.

**Comment by dirien** [comment]
See https://github.com/goreleaser/goreleaser/discussions/3515 for more details

**Comment by caarlos0** [comment]
lmnk if/how I can help!

**Comment by dirien** [comment]
Looks like Azure DevOps agents use now latest version of node. I need to check this and then I can update the Axiom version.

**Comment by dirien** [comment]
Fixed with #584
